### ISSUE TITLE
Lat / Lng defaults not set properly for Mashups

### ISSUE THREAD

**Issue by pippinsplugins** [WordImpress/google-maps-builder#100]
The UI says that the fields from Maps Builder are the defaults, but `_edit_lock` is the one selected: 
![screen shot 2015-08-26 at 10 38 51 am](https://cloud.githubusercontent.com/assets/1034109/9498313/c46518fc-4bde-11e5-8a0c-adfabfcb09bc.png)

**Comment by mathetos** [comment]
Gotta clear the Transients. I think you've got a fancy tool for that ;-)

@DevinWalker is working on updating that to work differently

**Comment by pippinsplugins** [comment]
Ah!

**Comment by DevinWalker** [comment]
Hmm, I'm pretty sure this should be fixed as of current Pro version. I'll swing back around and test again.

**Comment by DevinWalker** [comment]
Ok just tested again and it appears working properly from the latest updates.
