### ISSUE TITLE
Map theme set to none but showing Aqua

### ISSUE THREAD

**Issue by pippinsplugins** [WordImpress/google-maps-builder#101]
I was playing with the map themes (super awesome) and noticed a small bug.

I selected the Aqua theme in the editor to preview it and then changed it back to "None" for the default.

Editor: 
![screen shot 2015-08-26 at 10 41 24 am](https://cloud.githubusercontent.com/assets/1034109/9498359/0362b640-4bdf-11e5-9b58-766233397c0c.png)

Frontend:
![screen shot 2015-08-26 at 10 41 36 am](https://cloud.githubusercontent.com/assets/1034109/9498362/0bc2805e-4bdf-11e5-8bb0-4c9765c9c192.png)

**Comment by DevinWalker** [comment]
Looks like themes may be sticking to the frontend incorrectly
