### ISSUE TITLE
Get Directions Link on Front-end

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Google-Maps-Builder#103]
In the Maps Builder when you add a new marker it adds a "Get Directions" link into the infobubble. I don't see that happening on the front-end. That would be really useful.

![get-directions-link-infobubble](https://cloud.githubusercontent.com/assets/930724/9506318/478dd418-4bfc-11e5-8e98-46d6354b3b7c.jpg)

**Comment by DevinWalker** [comment]
Looks like I may have forgotten to add that on the frontend...

**Comment by DevinWalker** [comment]
@lchski can you take this one on? Directions are a pro only feature FYI

**Comment by lchski** [comment]
@DevinWalker it looks like this feature is actually found in the core repo. Clicking the link just opens a new tab with Google Maps, getting the directions from your current location to the one in the marker. I know that directions on the map are a pro-only feature, but is this a pro-only feature, then, if it’s in the core repo?

**Comment by lchski** [comment]
@DevinWalker, just wanted to ping you on this again—should I do the work in the core or pro repo? The feature is currently in the core repo. It’s not actually inline directions display, it opens a new tab with Google Maps open. Thanks!

**Comment by DevinWalker** [comment]
Hey @lchski thanks for pinging me again. To confirm, this directions feature *should* be in the core repo as it links out to Google for the directions. This should appear on both the frontend/backend of the info window content.

**Comment by lchski** [comment]
Cool, thanks Devin. I’ll get on this tonight or tomorrow morning.

**Comment by lchski** [comment]
PR for this is in core.
