### ISSUE TITLE
error on creation of new map / post

### ISSUE THREAD

**Issue by ifyouwillit** [WordImpress/google-maps-builder#104]
Warning: Invalid argument supplied for foreach() in /home/content/p3pnexwpnas10_data03/25/2746725/html/wp-content/plugins/google-maps-builder/includes/libraries/metabox/includes/CMB2_hookup.php on line 186

**Comment by DevinWalker** [comment]
This was fixed yesterday: https://github.com/WordImpress/google-maps-builder/issues/98
