### ISSUE TITLE
Warning using Desktop Server

### ISSUE THREAD

**Issue by leonmagee** [WordImpress/google-maps-builder#107]
I get the following warning after activating the plugin:

Warning: Invalid argument supplied for foreach() in /Users/leonmagee/Documents/Websites/www.gsphone-new.dev/wp-content/plugins/google-maps-builder/includes/libraries/metabox/includes/CMB2_hookup.php on line 186

**Comment by DevinWalker** [comment]
Hey Leon - are you using the latest version. This should be fixed in https://github.com/WordImpress/google-maps-builder/issues/98

**Comment by DevinWalker** [comment]
@mathetos is going to send you the latest version here momentarily. Thanks for checking out the plugin!
