### ISSUE TITLE
Ditch ThickBox in Favor of Magnific Popup

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/google-maps-builder#11]
Thickbox is terrible. We need to drop the usage from our plugin in favor of magnific popup, which is far superior.

**Comment by mathetos** [comment]
Agreed!

**Comment by kalenjohnson** [comment]
Thirded!

**Comment by royboy789** [comment]
Why Magnific vs. Featherlight?

**Comment by kalenjohnson** [comment]
I've never heard of Featherlight

**Comment by royboy789** [comment]
https://noelboss.github.io/featherlight/

**Comment by robneu** [comment]
+1 for Featherlight. 

If you end up adding it, you can avoid conflicts with our plugin by doing something [like this](https://github.com/wpsitecare/wp-featherlight/blob/develop/includes/class-scripts.php#L175-L188).

**Comment by royboy789** [comment]
but then it'd need to make sure the user has your plugin installed too, OR integrate it into the core development of this plugin, which seems like a waste, no?

**Comment by robneu** [comment]
You don't need to check to make sure a filter exists. Core handles that.

**Comment by royboy789** [comment]
Yea but what if the user doesn't have the plugin installed? So we'd need to integrate the WP plugin vs just checking if your (or anything using featherlight) plugin exists and if not enqueue the JS library ourselves.

**Comment by mathetos** [comment]
Same thing can happen with Magnific or others. Tons of themes and plugins love to bake in theses lightboxes in one way or another without providing options for overriding them or conditionally disabling them. We get it plenty with QuickCheckout. If we can find a solid solution to completely avoid such conflicts that'd be awesome... other than forking and renaming all the functions.

**Comment by robneu** [comment]
I think you're misunderstanding. You would enqueue the script in your plugin however you want, then add a filter for ours on pages where your plugin is loading the script. 

You don't need to check to see if our plugin is active to add the filter. If the plugin isn't installed, nothing will happen.

**Comment by mathetos** [comment]
My comment comes more from the init script that these all use. When that same init is called multiple times on the same page for different reasons it can get hairy. 

Rob's script is perfect for WPFeatherlight, but we can't put in lightbox killers for every single instance out there.

**Comment by robneu** [comment]
@mathetos Sorry about that, my reply was meant for @royboy789 and I don't think that was clear since we both posted at about the same time.

**Comment by royboy789** [comment]
@mathetos if only we could.. kill them all. Sorry @robneu didn't get it. If we decide to move forward with featherlight we'll keep it in mind.

**Comment by robneu** [comment]
Maybe we should consider disabling the packed scripts by default? I really hate the idea of loading 4 individual scripts for our plugin, but it would make for less compatibility issues...

**Comment by royboy789** [comment]
Default, you load everything that is necessary, there is no good way to check dependencies right now in WP, as far as scripts go.

**Comment by robneu** [comment]
We do that currently, but I adopted a method similar to Jetpack where we load a packed and minifed version rather than each of the individual scripts. 

It cuts down on load times by reducing 4 http requests to 1. The issue is that it also means our individual script handles aren't exposed to be used/overridden by default. There's a filter in the plugin to load the unpacked versions rather than the packed one, but it's not the default.

**Comment by chriswallace** [comment]
I would never automatically minify and concatenate assets in a plugin without giving the user the option to load the original scripts/styles.

**Comment by robneu** [comment]
@chriswallace There are more than enough methods in the plugin to modify/disable script and style loading, it's mainly just a question of what should be the default.

My general feeling is that the default should be what's best for most users which is fewer scripts loading on the front end.

**Comment by mathetos** [comment]
Somehow @robneu got us all talking about HIS plugin now on OUR thread... hrumph!

**Comment by robneu** [comment]
It's a gift I have. :heart_eyes:

**Comment by DevinWalker** [comment]
I'm down with using featherlight. If it has comparable feature sets, which I don't doubt it does, let's do it.

**Comment by royboy789** [comment]
Featherlight is just a lightbox, a very lightweight lightbox. I'll let @robneu tell you more about his plugin :stuck_out_tongue:
