### ISSUE TITLE
Loading GIF 404

### ISSUE THREAD

**Issue by JustinSainton** [WordImpress/google-maps-builder#113]
Getting a 404 on the loading-large.gif file.

It's because it's named loading-large.GIF, and that's case-sensitive.  Should standardize on lower-case throughout and it should be resolved.

**Comment by DevinWalker** [comment]
I saw that... thought I fixed it. Guess not. :(

**Comment by JustinSainton** [comment]
If that's the biggest failure in your launch, I think you're doing alright :dancer:

**Comment by DevinWalker** [comment]
This is fixed in 2.0.1
