### ISSUE TITLE
Make infowindow templatable

### ISSUE THREAD

**Issue by JustinSainton** [WordImpress/Google-Maps-Builder#114]
As it stands, overriding the infowindow is a little...cumbersome.

To do so, I have to do things like this:

``` php
add_filter( 'gmb_mashup_infowindow_content', function( $response, $marker_data, $post_id ) {

    $response['infowindow'] = str_replace( '</div>', '<p class="place=link"><a href="' . get_permalink( $post_id ) . '">Learn More</a></p></div>', $response['infowindow'] );
    return $response;

}, 85, 3 );
```

It would be _super duper sweet_ to be able to just override it (like we can with public.php via Google_Maps_Builder_Engine::get_google_maps_template) with a template file.

**Comment by DevinWalker** [comment]
TOTALLY agree with this. We don't want you to have to do any of that str_replace stuff....

**Comment by JustinSainton** [comment]
:+1: More than happy to submit PRs to the private Pro repo if that's helpful.  The get_google_maps_template() needs a bit of work to function as expected (it doesn't take in to account Windows filepaths or parent themes)

**Comment by DevinWalker** [comment]
I'll add you now to our Beanstalk repo. We appreciate any contribution efforts :) 

I also want to clean up the js A LOT on the admin side. It needs to be more class based without all this spaghetti function calls... but hey that's MVP.

**Comment by DevinWalker** [comment]
Which email should I add?

**Comment by JustinSainton** [comment]
justinsainton@gmail.com works great. and believe me, I appreciate as much as any (and more than most) all of the work that goes into these launches and getting a 1.0 out the door. you guys are doing a great job.

**Comment by DevinWalker** [comment]
Thanks for the kind words. I just sent the invite over.
