### ISSUE TITLE
Settings Tabs are janked

### ISSUE THREAD

**Issue by mathetos** [WordImpress/google-maps-builder#120]
Settings tabs are not behaving well. Verified locally and on our demo site.

![settings-tabs-janked](https://cloud.githubusercontent.com/assets/930724/9774871/340f482c-5700-11e5-9f8f-1ad2d53d1d6f.jpg)

**Comment by DevinWalker** [comment]
Oh yeah I noticed that too when the panel is shown... definitely needs a'fixin!
