### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by mathetos** [WordImpress/google-maps-builder#14]
We should handle Google Maps language output natively. Haven't dug into it, but I'm hoping that the Maps API has a language endpoint that would handle that automatically considering that it's Google. That would enable localized language output of all the Maps strings. See this support ticket:
https://wordpress.org/support/topic/localisation-of-map?replies=1#post-7097690

Just to clarify, I'm not talking about the plugin translating strings, but instead just letting the Google Maps API output it's own translated strings for the Maps output.

**Comment by dantahoua** [comment]
Yes, great, sure there is something for that in the API, google is so localisable!

**Comment by royboy789** [comment]
So not to effect anything outside of the map itself?

**Comment by mathetos** [comment]
Yes, in this case. Basically, the plugin is already Localized, but the Google Maps language strings are handled by the Google Maps API, not the plugin. We have a similar feature with our Open Table Widget which is available in different countries.

**Comment by dantahoua** [comment]
So we "just" have to find where to pass the language setting to google to be sure it show string in the good localisation. :)

**Comment by mathetos** [comment]
This looks like everything we need:
https://developers.google.com/maps/documentation/javascript/examples/map-language

**Comment by dantahoua** [comment]
Yes! "language=xxx". So you will pass the string of the language  use by wordpress, but here in Canada we make a lot of multi-lang website (fr / en) , so I wonder if the wordpress localisation code change when we change the front-end language with Polylang or WPML... Localisation can give you headache sometimes... :earth_americas:

**Comment by DevinWalker** [comment]
From the docmentation found here: https://developers.google.com/maps/documentation/javascript/basics#Language

> The Google Maps API uses the browser's preferred language setting when displaying textual information such as the names for controls, copyright notices, driving directions and labels on maps. In most cases, this is preferable; you usually do not wish to override the user's preferred language setting. However, if you wish to change the Maps API to ignore the browser's language setting and force it to display information in a particular language, you can add an optional language parameter to the <script> tag when including the Maps API JavaScript code, specifying the language to use.

Perhaps we can have an option to override this, but I think that's a Pro feature. Thoughts @mathetos @dantahoua

**Comment by DevinWalker** [comment]
Perhaps we can have an option to override this, but I think that's a Pro feature. Thoughts @mathetos @dantahoua

**Comment by mathetos** [comment]
It's basically an extension of localization. We should support that in core.

**Comment by DevinWalker** [comment]
I don't think it's a good idea to allow the user to override Google's preferred localization settings. Consider it like this... I want to go to Italy and Google Bed and Breakfasts. The B&B in Italy has a website that runs our plugin. If they set the default language to Italian, I'm left with that version no matter what and I don't speak Italian. 

The best option would be for the user to switch the language on their own. Though, I still don't think that's a good idea. People view Google maps on all sorts of browsers and Google stores their preference. They will serve up maps in the language they prefer... why should we interfere and possible degrade that experience?

**Comment by dantahoua** [comment]
Sometimes you want to force a localisation... And even if my browser is in French, the google map was showing in English on the website I made, strange...

**Comment by DevinWalker** [comment]
This has been integrated in the Pro version that will soon be released so I'm closing this one out.
