### ISSUE TITLE
#infobubble-content exceeds bubble width on mobile

### ISSUE THREAD

**Issue by mathetos** [WordImpress/google-maps-builder#15]
See details and the CSS fix here:

https://wordpress.org/support/topic/mobile-screen?replies=4#post-7162714

**Comment by DevinWalker** [comment]
I'm not able to reproduce this... I see the height exceeded, which is a separate issue.

**Comment by mathetos** [comment]
Go here: http://learn.mattcromwell.com/maps-test/

Shrink the screen to around 400px wide. Hit refresh. Click on the Map Marker and you'll see the problem. It's caused by the `min-width` rule for the `#infobubble-content` style in our stylesheet.

![bubble-content-width-problem](https://cloud.githubusercontent.com/assets/930724/8812188/881da6d4-2faf-11e5-8a0b-fcf681bbdbc8.png)

**Comment by mathetos** [comment]
The fix I suggested in the Repo ticket is to either remove the min-width rule completely, or just set it to `min-width: inherit`

**Comment by DevinWalker** [comment]
Is that twenty thirteen?

**Comment by mathetos** [comment]
No, that's Make. It's the same behavior that the original ticket had (which isn't available any longer). But regardless, the min-width is what is forcing that behavior.

**Comment by DevinWalker** [comment]
I wasn't able to reproduce that yesterday when looking into it on twenty fifteen. Is this with the current master branch or the wp.org version?

**Comment by mathetos** [comment]
wp.org I'll try with the latest from here.

**Comment by DevinWalker** [comment]
Removing from milestone until reproduced

**Comment by mathetos** [comment]
Just tested with latest from Git and it's resolved.
