### ISSUE TITLE
Move core lib into root using composer custom install directory

### ISSUE THREAD

**Issue by Shelob9** [WordImpress/Google-Maps-Builder#154]
@shelob9 Do this in pro true

**Comment by Shelob9** [comment]
Remembered why I can't do this -- can't use composer/installers to set custom install path for package, also this: https://github.com/composer/installers#should-we-allow-dynamic-package-types-or-paths-no

Closing as sad trumpets play next to @DevinWalker desk

**Comment by DevinWalker** [comment]
![273055277e3e4bdb51b7274fea77b471](https://cloud.githubusercontent.com/assets/1571635/13368432/1691997e-dc9f-11e5-981b-fed338dd119e.jpg)

**Comment by Shelob9** [comment]
https://media.giphy.com/media/mbPqOzyASJzB6/giphy.gif
