### ISSUE TITLE
UI bug in Google Maps > Settings

### ISSUE THREAD

**Issue by sstruemph** [WordImpress/Google-Maps-Builder#160]
I have a local site running Maps Builder Pro 2.0.2. On larger monitors the settings tabs are aligned at the top right. At first I couldn't find them and realized they were off to the side.

![admin-bug](https://cloud.githubusercontent.com/assets/3521793/14052132/e8426564-f295-11e5-943c-23ea7cf20dad.png)

**Comment by DevinWalker** [comment]
Fixed as of: 9b184b7cc4998331a40c56144d00a004426c169d
