### ISSUE TITLE
getCurrentPosition() and watchPosition() are deprecated on insecure origins

### ISSUE THREAD

**Issue by hiteshthakor** [WordImpress/Google-Maps-Builder#161]
please i am stuck , everything is working on localhost but on production site not working

**Comment by hiteshthakor** [comment]
![error](https://cloud.githubusercontent.com/assets/19173057/14991397/ccfc4024-117e-11e6-9eb4-e06855acb7da.png)

**Comment by DevinWalker** [comment]
Please ensure you have SSL enabled on your site for it to work properly.
