### ISSUE TITLE
Map Icons library needs to be updated

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Google-Maps-Builder#163]
A lot of recent updates have been made to this library:
https://github.com/scottdejonge/map-icons/commits/master

And it's noticed by our users as well:
https://wordimpress.com/support/topic/access-to-full-map-icons-library/#post-33637

**Comment by kevinwhoffman** [comment]
This library is no longer supported per the [author's comment](https://github.com/scottdejonge/map-icons/issues/60#issuecomment-265030528).

We should decide whether it is worth pulling the latest available version of that library, leaving it as is, or removing it.

**Comment by kevinwhoffman** [comment]
Let's move forward with updating the map-icons library. I'm currently seeing it in both the Free and Core repos, so let's make sure it's only in one place going forward.

- Free - https://github.com/WordImpress/Google-Maps-Builder/tree/master/includes/libraries/map-icons
- Core - https://github.com/WordImpress/Maps-Builder-Core/tree/master/includes/libraries
