### ISSUE TITLE
Featured Image shows in info bubble even when disabled

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Google-Maps-Builder#165]
@sstruemph commented on [Mon May 02 2016](https://github.com/WordImpress/Maps-Builder-Pro/issues/81)

Featured Image is displaying in info bubble with mashup even when "Show Featured Image" is disabled.

Issue was reported by support ticket. I replicated locally with WP 4.5.1 and Maps Builder 2.0.2.

![featured-image-1](https://cloud.githubusercontent.com/assets/3521793/14964697/fffcc144-106e-11e6-8ab1-b062f653db74.png)

![featured-image-2](https://cloud.githubusercontent.com/assets/3521793/14964710/0633e574-106f-11e6-8225-a91488e85da1.png)

---

@DevinWalker commented on [Fri May 13 2016](https://github.com/WordImpress/Maps-Builder-Pro/issues/81#issuecomment-219170093)

Nice featured image!

**Comment by DevinWalker** [comment]
Hey @lchski I see it is removed from the **backend** as expected:

![screen shot 2016-08-01 at 4 39 06 pm](https://cloud.githubusercontent.com/assets/1571635/17312291/79ef7b52-5806-11e6-8ad2-2edb8ad28e86.png)


but it is *still* displaying on the **frontend**:

![screen shot 2016-08-01 at 4 37 49 pm](https://cloud.githubusercontent.com/assets/1571635/17312279/624b09e4-5806-11e6-9c06-2a5e6dfe0b6e.png)

Can you check into that for me?

**Comment by DevinWalker** [comment]
Sorry @lchski my bad I was pulling down in one environment and reviewing in another... it's looking good now.

**Comment by sstruemph** [comment]
Tested locally with Pro version. The featured image is not showing with the setting:
Show Featured Image: Yes

There is an error although the error is there even if I have "Show featured image" set to No.

google-maps-builder.min.js:1
Uncaught TypeError: gmb.info_window.panToView is not a function
