### ISSUE TITLE
Make CSS stricter to avoid theme conflicts with images in the map

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Google-Maps-Builder#169]
@mathetos commented on [Thu Oct 22 2015](https://github.com/WordImpress/Maps-Builder-Pro/issues/12)

As seen [here](https://wordpress.org/support/topic/interactive-map-not-100-working-missing-details-and-tools-not-working), forcing `img {max-width: 100%, height: auto}` on the content area can create trouble with Google Maps. 

We should force some styles on the images in the map perhaps with inline styles to avoid this kind of headache.

---

@DevinWalker commented on [Thu Oct 22 2015](https://github.com/WordImpress/Maps-Builder-Pro/issues/12#issuecomment-150448935)

I thought we already did this... guess not!

**Comment by nishitlangaliya** [comment]
@mathetos , @DevinWalker ,

As per suggestion I have made the adjustment in css and make it forcefully apply css to our MAP. So the other themes common css do not affect into the map. I also went through the customer's site which is given in support https://wordpress.org/support/topic/interactive-map-not-100-working-missing-details-and-tools-not-working/.   To verify this changes by adding our css changes into inspect element tools. and it works. 

Please check for the same and let me know if any changes required.

Thanks
