### ISSUE TITLE
Loading Google Maps API in China

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Google-Maps-Builder#17]
See: https://developers.google.com/maps/faq#china_ws_access
Section on loading maps in China.

**Comment by DevinWalker** [comment]
This is a low priority - bumping off 2.2

**Comment by nishitlangaliya** [comment]
@DevinWalker ,

For this issue I have implemented GeoIP2 library Ref https://github.com/maxmind/GeoIP2-php and Made PR https://github.com/WordImpress/Maps-Builder-Core/pull/67

Thanks
