### ISSUE TITLE
Link to "Get an API Key" is incorrect

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Google-Maps-Builder#170]
@mathetos commented on [Thu Jul 07 2016](https://github.com/WordImpress/Maps-Builder-Pro/issues/91)

This link:
![2016-07-07 13_35_52-google maps builder settings give plugin dev wordpress](https://cloud.githubusercontent.com/assets/930724/16668924/d39f40ce-4447-11e6-8262-0bfe3fb247ba.png)

Goes here:
https://developers.google.com/maps/documentation/javascript/tutorial#api_key

Should be this:
https://developers.google.com/maps/documentation/javascript/get-api-key#get-an-api-key

**But really:**
We should point to our own site where we can update our content whenever Google changes their docs again. This will be the right URL on our site once it's live (soon):
https://wordimpress.com/documentation/creating-a-maps-api-key/ ‎

**Comment by DevinWalker** [comment]
Fixed that
