### ISSUE TITLE
Welcome Message Borking Settings Tab and Spacing Issue

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Google-Maps-Builder#171]
@DevinWalker commented on [Thu Mar 10 2016](https://github.com/WordImpress/Maps-Builder-Pro/issues/63)

See:

When the settings screen welcome appears it pushes the tabs to the right
![screen shot 2016-03-10 at 11 45 28 am](https://cloud.githubusercontent.com/assets/1571635/13682208/a828aae2-e6b5-11e5-9925-b17c467f2196.png)

Also there needs to be a space here:
![screen shot 2016-03-10 at 11 45 38 am](https://cloud.githubusercontent.com/assets/1571635/13682228/bc7d7108-e6b5-11e5-9bb2-8300369094f4.png)

**Comment by DevinWalker** [comment]
Both these are fixed now
