### ISSUE TITLE
Users aren't intuitively finding where to customize the Marker Icons

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Google-Maps-Builder#173]
@mathetos commented on [Mon Nov 02 2015](https://github.com/WordImpress/Maps-Builder-Pro/issues/13)

Several users are not finding the ability to customize the marker without very specific instructions. Makes for a clunky user experience. 

Customer feedback on this issue here:
- https://wordimpress.com/support/topic/cant-add-custom-marker/#post-31608
- https://wordpress.org/support/topic/after-201-ugrade-custiom-marker-icon-vanished?replies=3
- https://wordpress.org/support/topic/marker-icons-%E2%80%93-how-to-see-all-icons-that-come-with-the-font?replies=7 (this one isn't as specific to this issue, but still tangentially relevant)
### My proposal

There's probably more we could do to emphasize customizing the Infobubbles in general, but once they've clicked on the "Pencil" icon, I think the following change would make it much more intuitive to know how to customize the marker:
#### Currently:

![customize-marker-current](https://cloud.githubusercontent.com/assets/930724/10892300/7c5e9dfe-8157-11e5-8a3d-c3fa06afff9a.jpg)
#### Proposed:

![customize-marker-proposal](https://cloud.githubusercontent.com/assets/930724/10892303/826bf4e4-8157-11e5-8b74-3d24f9da7623.jpg)

**Comment by nishitlangaliya** [comment]
@kevinwhoffman ,

As per suggestions on comment https://github.com/WordImpress/Google-Maps-Builder/issues/173#issue-164427350 I have done the changes and made the PR https://github.com/WordImpress/maps-builder-core/pull/54 for the same.

Thanks
