### ISSUE TITLE
Display a Prompt to Enter Warning If No Google Maps API Key 

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Google-Maps-Builder#174]
**Scenario:** A new user installs and activates the plugin

**Problem:** Without a valid Google Maps API Key the plugin will not function properly

![screen shot 2016-07-07 at 3 54 13 pm](https://cloud.githubusercontent.com/assets/1571635/16672453/13095fde-445b-11e6-9c68-3b46658c9c5f.png)
![screen shot 2016-07-07 at 3 53 55 pm](https://cloud.githubusercontent.com/assets/1571635/16672454/130c51a8-445b-11e6-8ba1-9d8c9927bba4.png)

**Solution:**

- [ ] Create a prompt upon activation that checks for the API setting & whether it's filled in. If not, display the prompt with an explanation "As of June 22, 2016 Google requires an API key in order to display maps on your website. Don't worry, this is quick and easy. Find out [how to obtain an API key](https://wordimpress.com/documentation/maps-builder-pro/creating-maps-api-key/) and then click here (link to setting screen) to insert it once you receive one."

**Comment by kevinwhoffman** [comment]
I just experienced this error having not realized that an API key is now always required. As someone who has created many Google API keys in the past, I still find the process confusing. We need to make sure this requirement is very clear in multiple places. Here are a few recommendations.

1. Add a prompt upon installation as @DevinWalker suggested.
2. Update the text beneath the Google Maps API Key field on the Settings page to indicate that an API key is _always_ required (current text states it is not required).
3. Include messaging within the maps builder window itself (where it currently says Oops!) in the event that a user accesses that screen without having added an API key.

**Comment by DevinWalker** [comment]
Hey Kevin,

Thanks for the feedback. In response:

1. In process
2. This has been updated
3. Unfortunately, this is Google's own screen BUT the prompt will also display here from 1

**Comment by lchski** [comment]
@DevinWalker I think you’ve addressed this in the changes for 2.1; probably good to close.

**Comment by DevinWalker** [comment]
Just did some more adjustments to this and it's working nicely now.
