### ISSUE TITLE
API Error in Lookup is janked

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Google-Maps-Builder#176]
@mathetos commented on [Thu Jul 07 2016](https://github.com/WordImpress/Maps-Builder-Pro/issues/90)

If the API key is not entered correctly, the Mashup Lookup field throws an error. But the CSS on it makes the error totally incomprehensible:

![2016-07-07 13_09_40-edit post give plugin dev wordpress](https://cloud.githubusercontent.com/assets/930724/16668211/f986988a-4444-11e6-921a-b504d6699542.png)

This CSS should resolve it:

```
input#_gmb_mashup_autocomplete[placeholder*="Oops!"] {
    background-repeat: no-repeat;
    background-size: contain;
    padding-left: 35px;
}
```

**Comment by mathetos** [comment]
Review in case there are other places where we use the lookup feature. Perhaps in the Edit Map screen directly.

**Comment by lchski** [comment]
Interestingly, I seem to get this error even with an API key entered. As far as I can tell, I’ve got the proper API key and I put it in correctly, but I still get this error.

**Comment by DevinWalker** [comment]
@lchski did you add the Google Places to your API key?

**Comment by DevinWalker** [comment]
I need to confirm this is resolved prior to closing.

**Comment by DevinWalker** [comment]
Confirmed resolved. 
![screen shot 2016-08-03 at 1 06 38 pm](https://cloud.githubusercontent.com/assets/1571635/17380257/21833c08-597b-11e6-8fc1-d70d2807e538.png)
