### ISSUE TITLE
New API keys don't work with the Mashup Meta Box

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Google-Maps-Builder#184]
@mathetos commented on [Thu Jul 07 2016](https://github.com/WordImpress/Maps-Builder-Pro/issues/89)

## REPLICATION STEPS

* Create a new WordPress install
* Create a new Google Maps Javascript API Key
* Enter a the API key into the settings
* Add the Mashup metabox to the Post post type
* Search in the metabox for San Diego, and you'll see this:

![2016-07-07 13_09_40-edit post give plugin dev wordpress](https://cloud.githubusercontent.com/assets/930724/16668021/1fbc334e-4444-11e6-97ef-84a2e5a3a806.png)

**Comment by DevinWalker** [comment]
@lchski @mathetos I'll take care of this one since I already did in Google Places it would be faster.

**Comment by DevinWalker** [comment]
OK so here's how I resolved this:

1. New users who install the plugin will now see an activation banner welcoming them to the plugin and also prompting them to create a Google API key. This banner will appear when:
   1. they have no maps created
   2. the API key is missing
   3. they have not dismissed the banner yet.

![screen shot 2016-07-15 at 3 21 21 pm](https://cloud.githubusercontent.com/assets/1571635/16890031/d0a7833c-4a9f-11e6-830c-1d6ab6517f74.png)

2. User who experience an API authentication error on a CPT with mashups metabox enabled OR on the single google map creation screen will see:

![screen shot 2016-07-15 at 3 22 28 pm](https://cloud.githubusercontent.com/assets/1571635/16890050/f630b52e-4a9f-11e6-939c-ebd8384435ac.png)
