### ISSUE TITLE
Feature Request: Custom Map Marker Icon

### ISSUE THREAD

**Issue by kalenjohnson** [WordImpress/google-maps-builder#2]
This is a feature I wanted to implement for a project I'm working on. This is a first pass at it, I've added the file upload button and have it loading on the map. There is no check for image sizing, so I'm not sure if that should be implemented or if the client should be able to have free range of that.

https://github.com/kalenjohnson/google-maps-builder/commit/a987303a1cad2cd5ce15d9ec0ab396968cb37475

**Comment by alansutherland** [comment]
Custom icons don't work, I had to replace the default-marker png from the plugin folder

**Comment by DevinWalker** [comment]
Hey I added the filter `gmb_default_marker` which allows you to customize the default marker image without code. Check out this example:

```
/**
 * Google Maps Builder: Use a custom marker
 */
function my_prefix_custom_gmb_marker() {
	return get_stylesheet_directory_uri() . '/images/markerGreen.png';
}

add_filter( 'gmb_default_marker', 'my_prefix_custom_gmb_marker' );
```

Simply add this code to a custom functionality plugin or your theme's functions.php file and then customize the image path to the image you'd like to use. I'm using this one: 

![markergreen](https://cloud.githubusercontent.com/assets/1571635/8140550/59a9a1d4-1111-11e5-8cb6-151bf406a725.png)

And now it's looking good:

![custom-marker](https://cloud.githubusercontent.com/assets/1571635/8140585/c54630e2-1111-11e5-966e-4160545a2c88.png)

Note this will set the marker icon for the front and backend maps.

**Comment by alansutherland** [comment]
cool, thanks again :)
