### ISSUE TITLE
"Save Changes" tool tip stays on screen after saving changes

### ISSUE THREAD

**Issue by sstruemph** [WordImpress/Google-Maps-Builder#205]
Steps to replicate:

1. Create new map.
2. Click "Drop a marker"
3. Click on map to drop marker
4. Click "Save"
5. The "Save changes" tip stays
6. It will clear (disappear) when:

- The cursor moves off the page entirely
- The cursor moves on the "Save changes" tip and then back off

<div class="qtip-content" id="qtip-48676-content" aria-atomic="true">Save changes</div>

![save-changes-drop-marker](https://cloud.githubusercontent.com/assets/3521793/16778361/5317eb32-4833-11e6-9f02-d60416f99f5a.png)

**Comment by DevinWalker** [comment]
I noticed this too yesterday, super annoying...
