### ISSUE TITLE
Update Google Logo on Mashup Metabox

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Google-Maps-Builder#209]
@DevinWalker commented on [Fri Jul 15 2016](https://github.com/WordImpress/Give/issues/739)

Use the new "powered by" logo

![screen shot 2016-07-15 at 10 13 11 am](https://cloud.githubusercontent.com/assets/1571635/16882609/c8d5acae-4a74-11e6-9949-b3ab01016dd6.png)

---

@DevinWalker commented on [Fri Jul 15 2016](https://github.com/WordImpress/Give/issues/739#issuecomment-233019576)

Oops wrong repo ;)

**Comment by lchski** [comment]
Addressed by PRs in core and pro.

**Comment by DevinWalker** [comment]
Thanks @lchski
