### ISSUE TITLE
Mashup thumbnail option not working on backend

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Google-Maps-Builder#213]
When you select the "Yes" option the thumbnails do not appear as they should on the backend:

![mashup](https://cloud.githubusercontent.com/assets/1571635/17380698/497ce752-597d-11e6-94fa-0ea31a736580.png)

The option is being respected on the frontend.

**Comment by lchski** [comment]
It turned out to be more or less a duplicate of the problem in #165. Should be fixed via the PR in pro.

**Comment by DevinWalker** [comment]
merged - thanks!
