### ISSUE TITLE
Conflict with Vimeography plugin

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Google-Maps-Builder#216]
I wouldn't normally report a plugin conflict like this, but it seems like there might be something about this conflict which might reveal a broader issue.

* Install [Vimeography](https://wordpress.org/plugins/vimeography/)
* Create a gallery
* Add a Vimeography gallery to the same page as a Google Map

You should see this notice:
` Warning: Invalid argument supplied for foreach() in ...\wp-content\plugins\maps-builder-pro\vendor\wordimpress\maps-builder-core\includes\class-gmc-engine.php on line 120`

This happens both with Free and Pro.

**Comment by lchski** [comment]
A quick inspection indicates that the `$data` variable being created on line 108 of `maps-builder-core\includes\class-gmc-engine.php` isn’t proper JSON; it’s normal JavaScript, with a `var` statement at the beginning. I’ll trace the `$wp_scripts` setting to figure out what’s going on.

**Comment by lchski** [comment]
Ah, I’ve figured it out a bit more clearly now: somewhere we’re calling `wp_localize_script` and adding data without using `array_push_localized_script`; as a result, the string being passed into this function doesn’t look the way it expects, so it errors out. On it!

**Comment by lchski** [comment]
I’ve found the culprit: it has to do with Vimeography [manually calling `wp_enqueue_scripts`](https://github.com/davekiss/vimeography/blob/master/lib/renderer.php#L192), after it’s already run. There’s an old issue in Vimeography about it (https://github.com/davekiss/vimeography/issues/13), without any follow-up.

I’m not 100% how to proceed now: we know the issue doesn’t have to do with GMB, but rather with Vimeography. It’s non-standard and a bit dangerous, in my mind, to manually call `do_action('wp_enqueue_scripts')`, as Vimeography does. To tie us over and address this issue, we could run some kind of check to verify that our function doesn’t run twice, but the core issue is in Vimeography’s setup, not ours.

**Comment by mathetos** [comment]
@lchski Thanks for the research. I'll report to the user about your findings. Hope they fix it.

But your comment here:
> somewhere we’re calling wp_localize_script and adding data without using array_push_localized_script; 

Does that mean we can still improve how we do things, or that was your clue to find the problem in Vimeography?

**Comment by lchski** [comment]
@mathetos that was a clue to finding the problem; didn’t turn out to actually be the case.
