### ISSUE TITLE
Google Places Infobubble won't open again after closing out

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Google-Maps-Builder#224]
See example here:
![maps-builder-google-places-infobubble](https://cloud.githubusercontent.com/assets/930724/18896888/43f85e32-84da-11e6-8810-03f5bd920a74.gif)

## Steps to Reproduce
1. Search for a Place
2. It will open the infobubble immediately
3. Close out the infobubble
4. Either search for a new Place, or click on that Place again and the infobubble won't open again.

## Intended Behavior
The infobubble should always open when you click on the Place maker.

**Comment by DevinWalker** [comment]
I fixed this today

**Comment by DevinWalker** [comment]
See #223
