### ISSUE TITLE
No Info in Nearby Google Places InfoBubbles

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Google-Maps-Builder#225]
See example here:
![nearby-google-places-no-info](https://cloud.githubusercontent.com/assets/930724/18896966/ee519fba-84da-11e6-8f8d-68bc06a3b0f4.png)

## Steps to Reproduce

1. Create a map over a location
2. In "Google Places" check "Schools" or "Hotels"
3. The map will populate with nearby Places
4. Click on any nearby place and the infobubble will be empty

## Intended behavior
The infobubble should be populated with the relevant information as seen in our current demo:
http://mapsbuilder.wordimpress.com/demo/google-places-integration/

**Comment by DevinWalker** [comment]
Fixed here a71ff56e34d5bc2222e3ed0cb30c4f4120bba1c8
