### ISSUE TITLE
Fix bug with Give

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Google-Maps-Builder#227]
When you activate Maps Builder with Give activated you get a fatal error:

> ( ! ) Fatal error: Cannot redeclare on_create_blog() (previously declared in /app/public/wp-content/plugins/google-maps-builder/vendor/wordimpress/maps-builder-core/includes/install.php:98) in /app/public/wp-content/plugins/give/includes/install.php on line 219

**Comment by kevinwhoffman** [comment]
This can be closed as it was fixed in https://github.com/WordImpress/maps-builder-core/commit/a8f5a748d30b3dc59e6d49924ae6124a5b7085d4.
