### ISSUE TITLE
Fix compatibility issue with CMB2

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Google-Maps-Builder#228]
Per twitter and email conversation with Justin Sternberg

**Comment by kevinwhoffman** [comment]
Mash-up select boxes appear to be working correctly, and the email conversation links to a commit where the bug was fixed. https://github.com/WordImpress/Maps-Builder-Pro/commit/596b967289415cdbdcf935ab3d574d0fed4d36d3

I think this is okay to close.
