### ISSUE TITLE
JS Error only on IE11

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Google-Maps-Builder#232]
Not sure what can be done about this, it's very niche, but I've reproduced it in several different environments now:

## Step to Reproduce
* Install the latest Visual Composer (4.12.1)
* Install the latest Maps Builder Pro
* View the site in IE11 (not Edge emulation)
* Open IE's Developer Tools and refresh the page.
* You'll then see a Pause icon on the page and this error appears in the Console:

![ie11-visualcomposer-js-bug](https://cloud.githubusercontent.com/assets/930724/20121086/744acdb2-a5c4-11e6-9e58-0bb90ada0b54.jpg)

**Comment by mathetos** [comment]
Looks like this is not unique to Visual Composer, simply just an IE issue generally. Really odd.

https://wordpress.org/support/topic/error-with-internet-explorer-9-10-11/#post-8419205

**Comment by jarnoan** [comment]
Copied my comments from the wp.org support forum post:

With SCRIPT_DEBUG=true, I get the error at google-maps-builder.js line 700:

`var gmb_init = new CustomEvent('MapBuilderInit');`

According to https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent, CustomEvent constructor is not supported in IE. Following the example at
https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events#The_old-fashioned_way
I changed it to

```
var gmb_init = document.createEvent('Event');
gmb_init.initEvent('MapBuilderInit', true, true);
```

which seems to fix the problem (but I didn’t try further whether it causes any other problems…).

**Comment by mathetos** [comment]
Thanks @jarnoan for these details. Crazy IE!!

**Comment by DevinWalker** [comment]
@kevinwhoffman please implement the fix provided by @jarnoan and confirm ping me after a PR is created. I can then use my windows machine to check on IE.

**Comment by kevinwhoffman** [comment]
I just found that this was already resolved in https://github.com/WordImpress/maps-builder-core/issues/47. Matt confirmed it was tested and fixed.
