### ISSUE TITLE
Enhancement: Enhance the information shown in directions markers

### ISSUE THREAD

**Issue by sstruemph** [WordImpress/Google-Maps-Builder#238]
Currently the directions markers only show very basic information about the location. Would it be possible to enhance these markers to display more information in the infobubble?

Directions marker only shows basic info:
![directions-marker](https://cloud.githubusercontent.com/assets/3521793/22224858/d25460c4-e185-11e6-8890-387935e6f824.png)

Example with more info (Directions markers currently cannot display more info in the popup)
![maps-marker](https://cloud.githubusercontent.com/assets/3521793/22224860/d5f6819e-e185-11e6-9c7b-cf4a0b3db1b0.png)

**Comment by DevinWalker** [comment]
Unfortunately, those infobubbles are generated by Google and at this time it's not possible to customize them.
