### ISSUE TITLE
feat(admin-maps): replace 'Quick Edit' with 'Preview Map' in list table

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Google-Maps-Builder#25]
Quick edit is pretty worthless here... I think we should replace it with a map preview option because allows the user to preview the map before going into the post to edit:

![quick-view](https://cloud.githubusercontent.com/assets/1571635/8887446/1202ef2e-3237-11e5-80e4-65b798474623.png)

**Comment by mathetos** [comment]
Even better if the Preview would simply popup in a modal via AJAX rather than redirect to a new page. AJAX modal so all the maps aren't loaded to the page on pageload.

**Comment by DevinWalker** [comment]
Yeah that's what I'm saying

On Saturday, July 25, 2015, Matt Cromwell <notifications@github.com> wrote:

> Even better if the Preview would simply popup in a modal via AJAX rather
> than redirect to a new page. AJAX modal so all the maps aren't loaded to
> the page on pageload.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WordImpress/google-maps-builder/issues/25#issuecomment-124861970>
> .
>


-- 

Devin Walker

Founder & Lead Developer

P:

858-449-6460 <8584496460>

W:

http://wordimpress.com

433 G Street #201
San Diego, CA 92101 <https://goo.gl/maps/BePgp>
<https://www.facebook.com/wordimpressive>  <https://twitter.com/wordimpress>
  <https://plus.google.com/u/0/b/117062083910623146392/+Wordimpress/about>
<http://wordimpress.com/>

**Comment by nishitlangaliya** [comment]
@DevinWalker ,

As per suggestions I have added changes to remove quick edit link and preview map via ajax by adding below two PR:

https://github.com/WordImpress/Google-Maps-Builder/pull/267
https://github.com/WordImpress/maps-builder-core/pull/53

Thanks
