### ISSUE TITLE
Incompatible with PHP versions greater than 7.2

### ISSUE THREAD

**Issue by TobiasMalikowski** [WordImpress/Google-Maps-Builder#260]
Hi there, I want to report a bug. 

I'm using Google Maps Builder Pro 2.1.2 and PHP 7.2.7.
The PHP error log throws the following error: 

`PHP Fatal error:  Declaration of CMB2_Type_Textarea_Code::render() must be compatible with CMB2_Type_Textarea::render($args = Array)`

After some research I found out that this bug has been solved in CMB2 versions greater than 2.3.0 (latest version at the time writing this is 2.4.2).

[CMB2 issue on GitHub page](https://github.com/CMB2/CMB2/issues/1070)
[CMB2 troubleshooting for this issue](https://github.com/CMB2/CMB2/wiki/Troubleshooting#fatal-error-declaration-of-cmb2_type_colorpickerrender-or-similar)

So I kindly ask you to update your plugin dependencies to use a CMB2 version greater than 2.3.0.
This will fix the bug and let devs use the new PHP version for increased performance.

Thank you,

Tobias

**Comment by TobiasMalikowski** [comment]
Hey just scanned the plugin with a PHP 7.2 compatibility checker and also got this three warnings.
Would be nice if you could fix those too.

**google-maps-builder-pro/includes/admin/import-export/class-marker-exporter.php**
 168 | WARNING | INI directive 'safe_mode' is deprecated since PHP 5.3 and removed since PHP 5.4
 190 | WARNING | INI directive 'safe_mode' is deprecated since PHP 5.3 and removed since PHP 5.4

**google-maps-builder-pro/vendor/wordimpress/maps-builder-core/includes/admin/system-info.php**
224 | WARNING | INI directive 'safe_mode' is deprecated since PHP 5.3 and removed since PHP 5.4

Thanks, Tobias

**Comment by DevinWalker** [comment]
Thanks for reporting @TobiasMalikowski

**Comment by TobiasMalikowski** [comment]
@DevinWalker 
No problem, I'm glad that I could help. How will I know if my other issues are fixed (they got moved to the gmb pro repo, I have no access there)?

**Comment by DevinWalker** [comment]
@TobiasMalikowski we're not going to be moving them anymore. This is the repo we'll be working the issues from.

**Comment by nishitlangaliya** [comment]
@DevinWalker 

I have gone throgh the issue and for that I did troubleshoot on https://github.com/CMB2/CMB2/wiki/Troubleshooting#fatal-error-declaration-of-cmb2_type_colorpickerrender-or-similar
so for that I see that we will require to update CMB2 library to 2.3.0 to make compatible with php version > 7.2. So I talked with @ravinderk and as per our discussion he told we might dropout CMB2 and use our own settings API as per GIVE.

So Here we have two options.

1. Either we drop out CMB2 and implement give settings api with backward compatiblity.
2. We need to upgrade whole library CMB2 to version 2.3.0 in Google-Maps-Builder\vendor\wordimpress\maps-builder-core\includes\libraries\metabox

So would you please provide your suggestion here so I can move forward with your feedback.

Thanks.

**Comment by DevinWalker** [comment]
@nishitlangaliya dropping CMB2 would be a major undertaking that I'm not willing to go through now. So let's go with option 2 for the faster fix.

**Comment by nishitlangaliya** [comment]
@DevinWalker ,

As per suggestion I have updated the cmb2 library to 2.3.0 in maps-builder-core and done PR https://github.com/WordImpress/maps-builder-core/pull/51 for the same. 

Thanks
