### ISSUE TITLE
fix(google-maps-builder): TypeError: $(...).qtip is not a function in console for php version 7.2.0

### ISSUE THREAD

**Issue by nishitlangaliya** [WordImpress/Google-Maps-Builder#265]
## User Story

As a `Admin` I want fix js error in console `TypeError: $(...).qtip is not a function` so that I can add map.

This isssue only comes when we configure PHP version to 7.2.0.
 

## Current Behavior

`TypeError: $(...).qtip is not a function`  in file Google-Maps-Builder/vendor/wordimpress/maps-builder-core/assets/js/admin/admin-google-map.min.js?ver=2.1.2

## Expected Behavior

I expect it to working fine as working like version <= 7.1.4

## Steps to Reproduce
Please see the video

## Videos

Video Link: https://www.useloom.com/share/850d04f22aa147b2955045c6f958361c

**Comment by DevinWalker** [comment]
@nishitlangaliya I'm assuming this will be resolved when https://github.com/WordImpress/Maps-Builder-Core/pull/61 is released

**Comment by DevinWalker** [comment]
This has been resolved https://github.com/WordImpress/Maps-Builder-Core/pull/52
