### ISSUE TITLE
refactor: remove deprecated signed-in maps feature

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Google-Maps-Builder#275]
## User Story

As an `admin` I don't want to use `deprecated features` like `signed-in maps`. 

**From Google:** https://developers.google.com/maps/documentation/javascript/signedin

- [ ] Remove feature from Pro plugin

**Comment by nishitlangaliya** [comment]
@DevinWalker I see past thread and found that this issue is resolved in Release/2.1.2 https://github.com/WordImpress/Google-Maps-Builder/issues/231 .  I was also unable to see signed in settings in admin settings. can you please check for the same and let me know if any changes required.

Thanks
