### ISSUE TITLE
fix - fatal error for class not found

### ISSUE THREAD

**Issue by nishitlangaliya** [WordImpress/Google-Maps-Builder#279]
While testing with other issue I found class Google_Maps_Builder_Core_Admin not found fatal error.

**Comment by DevinWalker** [comment]
@nishitlangaliya in the future please try to make your issues more descriptive so we can understand them when reading. For instance, this should have a screenshot of the "fatal" (not fetal - that's much different of an error...) error.

**Comment by nishitlangaliya** [comment]
@DevinWalker , Sure I will take care about it and will provide more description when creating an issue. I have made the requested changes in PR

Thanks
