### ISSUE TITLE
Clustering

### ISSUE THREAD

**Issue by mathetos** [WordImpress/google-maps-builder#3]
Really interesting feature request with an example link. See @AlfonsoAB's reply (around comment 11).

https://wordpress.org/support/topic/major-development-beginning-now?replies=12

**Comment by DevinWalker** [comment]
Agree this would be cool for a Pro feature.

**Comment by kevinwhoffman** [comment]
+1 support for clustering.

On a recent project I had to develop a map of Italy where the initial zoom level of the map showed the entire country (http://celebrateditaly.com/map/). Most of the markers were in close proximity and focused around the major cities. Without clustering, it would be a mess of overlapping markers. With clustering, the initial view is kept clean and the clusters break down into more detailed views as the zoom level increases.

**Comment by DevinWalker** [comment]
Hey Guys, I've built this into the Pro plugin already. Closing this one out :)
