### ISSUE TITLE
Better method to toggle CMB2 fields

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Google-Maps-Builder#37]
Right now we toggle a lot of fields show/hide in the plugin and it's pretty messy. We should standardize this with a class for the master toggler and another for the toggled elements. It will make the code less bloated and future development easier for new toggled fields.

**Comment by nishitlangaliya** [comment]
@DevinWalker ,

Do you mean there should be one master toggle button somewhere in edit map screen and by click on that it should toggle all metabox present in edit map screen ?. I have created rough screenshot what I understand can you please review it and let me know your feedback?

![issue-37](https://user-images.githubusercontent.com/11435772/44320563-9a8d4800-a3f7-11e8-9375-12214d0ac7dd.png)


Thanks

**Comment by DevinWalker** [comment]
@nishitlangaliya I'm not talking about that in the UI. I'm talking about the JS code that's long and unwieldy for toggling elements in the UI. Closing this out because this would take a major refactor.
