### ISSUE TITLE
feat - Additional Admin Columns

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Google-Maps-Builder#38]
We should add more columns in the admin maps post listing view. I'm thinking:
- # of markers
- Map long/lat

![columns](https://cloud.githubusercontent.com/assets/1571635/9044630/b807c956-39d2-11e5-9539-ae67a1e0fbf5.png)

**Comment by kevinwhoffman** [comment]
I like the idea of displaying number of markers here. I also think a column for zoom level (0-21) would be helpful based on past experience with a client. They found it helpful to reference the zoom level of one map when creating another.
