### ISSUE TITLE
Disable and Hide Zoom and Satellite options

### ISSUE THREAD

**Issue by alansutherland** [WordImpress/google-maps-builder#4]
I'd like to be able to disable and hide the zoom and Map/satellite options for my maps. I have set Zoom control to None but this does nothing

**Comment by DevinWalker** [comment]
This is works now in the latest version on GitHub. We'll be releasing 2.0 on the repo once we work out a few more bugs and do thorough testing. Thanks for your submission!

**Comment by alansutherland** [comment]
Thanks :)
