### ISSUE TITLE
Add links to documentation

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/google-maps-builder#43]
The intro banner references documentation but there's no link...

![doc-link](https://cloud.githubusercontent.com/assets/1571635/9093965/2a6613f8-3b64-11e5-98c2-71afdf90d1d0.png)

**Comment by mathetos** [comment]
I wonder why...? I'm on it!

**Comment by DevinWalker** [comment]
Documentation links to: https://wordimpress.com/documentation/maps-builder-pro/
