### ISSUE TITLE
Cannot read property 'PlacesService' of undefined

### ISSUE THREAD

**Issue by jfarsen** [WordImpress/Google-Maps-Builder#60]
When adding the shortcode to a page, the map displays, but not the marker. The Chrome console show this error message :

Uncaught TypeError: Cannot read property 'PlacesService' of undefined
initialize_map @ google-maps-builder.min.js?ver=2.0:2
(anonymous function) @ google-maps-builder.min.js?ver=2.0:128
m.extend.each @ jquery.js?ver=1.11.2:2
m.fn.m.each @ jquery.js?ver=1.11.2:2
(anonymous function) @ google-maps-builder.min.js?ver=2.0:128
m.Callbacks.j @ jquery.js?ver=1.11.2:2
m.Callbacks.k.fireWith @ jquery.js?ver=1.11.2:2
m.extend.ready @ jquery.js?ver=1.11.2:2
J @ jquery.js?ver=1.11.2:2

**Comment by DevinWalker** [comment]
That's no good! I'm going to need to know how to reproduce this or see the problem live. Would you mind pasting in a comment here or emailing me at support(at)wordimpress.com your system info settings under Google Maps > Settings > System Info - And, even better... providing me a URL where this error is visible. 

I'm looking forward to squashing this one :)

**Comment by jfarsen** [comment]
Email with system info sent, unfortunately, it's a local DEV env, so can't share (easily)

**Comment by DevinWalker** [comment]
Ok I'll try to reproduce it

**Comment by DevinWalker** [comment]
This is resolved in 2.1 release.
