### ISSUE TITLE
"Hide Place Details" not working for individual markers

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/google-maps-builder#62]
When adding a marker based off a known location in Google Places, a gray box is added with address, phone, website and 5-star rating. I assume this is what you are referring to as "Place Details" in the marker settings.

These details may not always be desirable, so I checked "Hide Place Details" to see if that setting would hide the gray box but it didn't work. You can see below that the gray box still displays, even after Update.

![hide-place-details](https://cloud.githubusercontent.com/assets/1938671/9279031/ac83c1ee-4282-11e5-9eca-cae02ee13794.jpg)

**Comment by DevinWalker** [comment]
Thanks for the report. I'll be fixing it shortly here :+1:
