### ISSUE TITLE
Auto-populate markers from existing posts with location meta data

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/google-maps-builder#63]
### Background (Example Use Case)

I have over 200 posts in a CPT called Properties. Each post already has latitude and longitude coordinates stored in custom fields. Each post is also assigned to a custom taxonomy called Regions with terms as follows: England, Ireland, Scotland, Italy. I need to create one map for each Region and display those Properties on the map.

In summary, the content hierarchy looks like this:

* England
  * Property 1
  * Property 2
  * Property 3
* Ireland
  * Property 4
  * Property 5
  * Property 6...
* Scotland
* Italy

### The Problem

In order to add these Properties to a map, I currently have to create every marker individually and copy/paste those coordinates into the marker settings. Furthermore, adding new Properties in the future would require me to revisit the map editor every time in order to add a new marker.

### The Solution

Allow user to select a post type and/or taxonomy where existing posts with location meta data can automatically populate markers on an ongoing basis without having to return to the map editor for each new post. This would remove the tedious repetition of manually adding markers for posts that already have location meta data associated with them. Here are a list of feature requests that would make this process possible:

* Select post type to be used for auto-population of markers.
* Filter auto-populated markers based on taxonomy.
* Allow user to select custom fields where existing location meta data is stored (e.g. latitude, longitude). Users may have existing custom fields in place, so the ability for them to select the existing fields would be important.
* Bonus: Display the post's featured image in info box.

I've included a mockup of what these settings might look like below:

![markers-from-posts-v01](https://cloud.githubusercontent.com/assets/1938671/9281269/c859b04a-4291-11e5-9633-1c9089e867f2.jpg)

**Comment by DevinWalker** [comment]
Hey @kevinwhoffman we're totally working on this and your concept is perfect. Note: this is going to be a Pro feature. We're also going to have the option to add a metabox similar to the one you displayed above to various post types of the user's choosing which will allow them to add mashup markers on a map as well.

**Comment by kevinwhoffman** [comment]
@DevinWalker That's great to hear! And it makes sense that it would be a pro feature. I think having this functionality in place would increase the plugin's appeal by including those who already have posts w/ location meta data in place.

**Comment by DevinWalker** [comment]
Definitely! I agree. I'm going to close this one out since it's on the free repo but rest assured I'll be using your UI as a guide.
