### ISSUE TITLE
fix(builder): display existing marker's saved settings when editing

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/Google-Maps-Builder#64]
### The Problem

If I attempt to edit a marker's icon that has already been set in a past session, the saved icon settings do not appear. I have to start the icon editing process over from scratch. Let's say I just want to change the icon color. I can't do that without resetting all of the other icon options along with it.
### The Solution

When editing an existing marker's icon, display the saved settings as a starting point so tweaks can be made faster.

**Comment by DevinWalker** [comment]
The functionality was like as you propose in your solution. I had updated it to refresh the modal when a marker is saved awhile back because I remember there being an issue when editing multiple markers in succession. I'll need to review the issue again to get a better understanding on how to improve the UX for this.

**Comment by kevinwhoffman** [comment]
I did notice there was different behavior depending on whether I revisited the marker in the same session or a different session (after updating).

**Same Session** - The icon editor seems to maintain the colors from the _last_ edited marker. Ideally it should show the saved settings of the _current_ marker. I can see why it might be helpful to start with the previous markers settings, but only if I'm adding a _new_ marker. Also, only colors are maintained; the icon itself does not show the gold selection around the current icon.

**Different Session** - The icon editor is completely reset when revisiting an existing marker icon.

**Comment by kevinwhoffman** [comment]
## Acceptance Criteria

- [ ] When I edit an existing marker, the color and icon settings are pre-populated so I do not have to start from scratch to make a simple revision.
- [ ] When I add a second marker in the same session, the settings of the previous marker are used.

## Current Behavior

When I click this button...

![image](https://user-images.githubusercontent.com/1938671/44380487-a8b39500-a4d9-11e8-955f-aebab752d7ca.png)

I currently have to start over as if I'm editing a new icon.

![image](https://user-images.githubusercontent.com/1938671/44380446-65592680-a4d9-11e8-936c-f667cd054ddc.png)

## Expected Behavior

Instead I should see a window like this where the custom settings of the icon are populated immediately so I can continue editing the icon.

![image](https://user-images.githubusercontent.com/1938671/44380515-d6004300-a4d9-11e8-9e92-ec45e90bb031.png)

**Comment by nishitlangaliya** [comment]
@kevinwhoffman ,

As per suggestion I have made the changes to display saved settings while editing and creating map and made the PR https://github.com/WordImpress/Maps-Builder-Core/pull/57 for the same.

I have created how it works video.

https://www.useloom.com/share/aab3a693aa624685abff2095cbd193b8

**Comment by DevinWalker** [comment]
Nice job @nishitlangaliya looks good.

**Comment by nishitlangaliya** [comment]
@DevinWalker , Thank you :)
