### ISSUE TITLE
Use locations from Custom Post Types

### ISSUE THREAD

**Issue by mordant23** [WordImpress/google-maps-builder#65]
This would be a great solution for us if we could bulk add markers based upon location fields in custom post types and add post meta to the marker overlay. Is this type of feature on the roadmap or would it be easily extendable for us to add this feature ourselves?

**Comment by mathetos** [comment]
We're already building this out. It will be in the Pro version of the plugin. There's a lot of potential for how this can be implemented. But you can see a short conversation we had with another user about this idea here:

https://github.com/WordImpress/google-maps-builder/issues/63
