### ISSUE TITLE
UI Suggestions w/ Mockups

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/google-maps-builder#66]
After using the plugin quite a bit, I did some mockups to demonstrate my UI suggestions. These are just mockups that I put together by hacking around in developer tools, but if you like this direction, I am willing to help with the CSS to make it happen.

# UI Suggestions

1. **Blue accordion tabs:** Improves clarity by increasing visual contrast between accordion tabs and tab content.

2. **Bold field labels:** Makes it easier to scan the interface by differentiating the font-weight of field labels and field values.

3. **Full-width select fields:** Drastically improves the visual pathway of the UI (see Figure 1 below).

4. **Remove bottom border from field labels:** With full-width select fields (see above), the fields themselves now act as visual separator between content, making the bottom borders unnecessary.

5. **Red marker tabs:** The existing gray marker tabs background blend in and get lost in the UI. Markers are the stars of the show (as referenced in your logo) and they should call attention to themselves. Giving them high-contrast background-color allows them to stand out from the interface. The red also ties into your logo and the default marker color on the map (see Figure 2).

6. **Yellow alerts:** The alert about the Lat/Lng update requires action and it is important that user see it before leaving the editor. Making it yellow helps it to stand out more and denotes warning which is more appropriate than green which suggests success (see Figure 3).

7. **Bonus Branding Level Up**: I used colors from your logo so there's the side effect of your brand extending into the interface.

## Figure 1

Visual pathways shown in green (not part of the UI). The version on the right would significantly improve the speed of clicking around the plugin by placing most controls along a single vertical axis.

![maps-builder-ui-visual-pathways](https://cloud.githubusercontent.com/assets/1938671/9376540/70c61220-46dc-11e5-9b22-1fd9037f5f11.jpg)

## Figure 2

Marker suggestions shown on the right. Also note that the contrast of the blue tabs keep the sections of the accordion clearly separated even when multiple tabs are expanded.

![maps-builder-ui-markers](https://cloud.githubusercontent.com/assets/1938671/9376547/8aab89cc-46dc-11e5-9631-61618eac0f32.jpg)

## Figure 3

A full side-by-side comparison of the current interface on the left and my recommendations on the right:

![maps-builder-ui-full](https://cloud.githubusercontent.com/assets/1938671/9376561/c78fb962-46dc-11e5-80b0-e004d58266b2.jpg)

**Comment by DevinWalker** [comment]
First let me begin by saying that I really like what you have shown here and appreciate the thoroughness of your explanations. I would love to give you a Pro license so you can see all the new features we have built. The free plugin only shows some of the plugin's power. That said, the current UI is in need of a touch up, I agree. 

At first, I thought the color choices you made were a bit bold and would not mesh well with the WordPress interface. That's what we are trying to go for currently. BUT, it's grown on me and I think breaking up the sections with our branded colors is a good route to go to resolve some of the painpoints we've had. Also, I want to mention that your suggestions up to this point have been spot on.

I can implement this, but if you would like to take a stab before we launch 2.0 that would be most appreciated. 

We also need to test the upgrade process from the current WordPress.org version and this new version a bit more. I'm fairly confident in the process thus far but would feel better if a few others gave it a go.

**Comment by kevinwhoffman** [comment]
Thanks for checking it out. The major point I wanted to address was the issue of contrast. I actually started with a totally grayscale approach that I thought would mesh better with WP's default styles, and then started to layer in some color. I think the color helps to group related controls together. For example, it's obvious that the blue tabs belong to the same control group even when split up across the UI in an expanded state.

I definitely hear your point about clashing with the WP interface, but because you are launching in a full-screen modal, I think that gives you more freedom to define your own look. You also might consider allowing the user to customize these UI colors as a Pro feature.

As for my involvement, having never used version 1, I think I'd be more valuable in testing version 2. Definitely interested in the Pro features. I can also take on the CSS for the above UI if that helps.
