### ISSUE TITLE
Mashup Clustering Isn't Working

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Google-Maps-Builder#67]
When you add mashup markers and want them clustered it doesn't work.... yet!

**Comment by nishitlangaliya** [comment]
@DevinWalker ,

As this issue was for Pro Plugin I have created an issue under the pro plugin repository.
https://github.com/WordImpress/Maps-Builder-Pro/issues/109 and done PR for the same: https://github.com/WordImpress/Maps-Builder-Pro/pull/110 .

Thanks.

**Comment by DevinWalker** [comment]
@nishitlangaliya don't create duplicate issues anymore as we've discussed.

**Comment by nishitlangaliya** [comment]
@DevinWalker ,

This fix required to change in maps-builder-core repository so I have just created PR https://github.com/WordImpress/maps-builder-core/pull/50 there and just referenced this issue into that PR.

Thanks
