### ISSUE TITLE
Sidebar Google Maps default link location

### ISSUE THREAD

**Issue by paaljoachim** [WordImpress/google-maps-builder#69]
Hey guys

The feedback has begun...:)

I notice the default sidebar location of Google Maps is right below Pages in the Menu Position of 21.3. Why is it 21 dot 3? Have a whole number please.
Default location of Google Maps "should" be under WP Settings the menu position of 80.
It is very cool that you have this feature included!

Btw 
I have to click the Save Settings button twice to get the Menu Position to change. Play around with moving it around to different locations and you can see it is a little off. But that is a minor thing...

**Comment by mathetos** [comment]
Paal, the menu positioning is a really problematic aspect of dealing with Custom Post Types. The "hack" of adding decimal positions is to provide finer control of the position. We believe content (like maps) belongs up with Post/Pages, not far down with settings.
