### ISSUE TITLE
Location Lookup Marker Creation Fail Bug

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/google-maps-builder#7]
When you add a location via the "Location Lookup" field, for instance "USS Midway":

![add-marker-1](https://cloud.githubusercontent.com/assets/1571635/8139784/3839df56-110b-11e5-92f4-c3d6ef6371ff.png)

It add the marker properly in place BUT the marker's info window never opens AND when you try to click on it the page refreshes. 

![add-marker-2](https://cloud.githubusercontent.com/assets/1571635/8139804/52644f38-110b-11e5-9fdb-5b9af3fa99a1.png)

**Comment by royboy789** [comment]
fixed in commit ab740f8894f0cdce2bebb24094982cfe07e7b8cf
