### ISSUE TITLE
Map Options: Default Map Settings - top sentence

### ISSUE THREAD

**Issue by paaljoachim** [WordImpress/google-maps-builder#70]
The top sentence under Map Options

"The following settings change the default map options that display when created a new map."
I suggest changing it to:
After having made a new map change how the default map options display.
or
Change how the default map options display after having made a new map.

**Comment by DevinWalker** [comment]
Good catch

**Comment by DevinWalker** [comment]
Updated to: "The following settings control global map display options and preferences"

**Comment by paaljoachim** [comment]
Good one Devin!
