### ISSUE TITLE
Interlocking width and height in the Map Size option?

### ISSUE THREAD

**Issue by paaljoachim** [WordImpress/google-maps-builder#71]
Should width and height be interlocked? As in click a lock and change one and the other changes automatically to adjust to the new size.

Not sure about this but I thought I would mention it anyway.

Lets say one decides on a ratio. On clicks the lock to unlock then change the ratio between height and width. Then clicks the lock. Later when adjusting width or height the ratio will be intact (similar to resizing with shift held in in Photoshop).

**Comment by mathetos** [comment]
I can see that being useful for images, but not so much for maps. Unless we get a lot more feedback that has specific usecases where that feature would be necessary I don't think we'll implement this.
