### ISSUE TITLE
Map Options: Map Location wording

### ISSUE THREAD

**Issue by paaljoachim** [WordImpress/google-maps-builder#72]
Map Location 
Geolocate Position Yes - No
"When creating a new map the plugin will use your current longitude and latitude for the base location. If you see a blank space instead of the map, this is probably because you have denied permission for location sharing. You may also specify a default longitude and latitude by turning off this option."

<b>Adjusting wording:</b>

Map Location 
Geolocate Position Yes - No

Yes - When creating a new map the plugin will use your current longitude and latitude for the base location. 
No - Set your own default longitude and latitude position. Selecting no and leaving the coordinates blank you will likely see a blank space instead of the map.

**Comment by DevinWalker** [comment]
Hmm not sure about this one. I think it's worded fine.  @mathetos what do yo think?

**Comment by paaljoachim** [comment]
My mind is turning around on this. I'll explain..

"When creating a new map the plugin will use your current longitude and latitude for the base location. If you see a blank space instead of the map, this is probably because you have denied permission for location sharing. You may also specify a default longitude and latitude by turning off this option."

Using Probably because and denied permisson and then location sharing is a lot of words to get the head around.

I will rephrase it another way:
If you have set Geolocate position to no you might get a blank space instead of a map. Be sure to set your own default longitude and latitude position.
To use your own  current longitude and latitude for the base location set the option to yes.

The reason for adding Yes or No in front is to be really clear on what the differences are.

**Comment by DevinWalker** [comment]
Ok I updated the wording a bit based on your feedback.
