### ISSUE TITLE
Add new - Introducing Map Builder dialog box. Link to plugin settings.

### ISSUE THREAD

**Issue by paaljoachim** [WordImpress/google-maps-builder#74]
Introducing the MAP Builder (initial help text dialog box)
"Enable the view by default within the plugin settings...."
 ——> 
Have plugin settings as a link that opens a new tab so the user can enable it right away. If they choose to do so.

**Comment by DevinWalker** [comment]
Definitely, just got lazy and didn't include it

**Comment by DevinWalker** [comment]
This is fixed.

**Comment by paaljoachim** [comment]
Great!
