### ISSUE TITLE
fix - Media Library text search not working for custom marker icons

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/Google-Maps-Builder#78]
The Media Library text search is not clickable when setting a custom icon for both individual markers and mashup markers. Clicking the box should establish focus and allow user to start typing, but nothing happens. Makes it difficult to find a custom marker in a large library.

![image](https://cloud.githubusercontent.com/assets/1938671/9423958/da281e9e-48a7-11e5-8b81-23aea52f5f68.png)

**Comment by mathetos** [comment]
I really wonder whether it's wise for us to lean on the Media Library for this purpose. I wonder if we'd be better off just using the default Upload feature and saving custom markers to `/wp-content/uploads/maps-markers/` And then only see those images when you go to choose one. 

@DevinWalker Thoughts?

**Comment by DevinWalker** [comment]
I'd rather just use the media editor. It's annoying for many users when a plugin creates new directories and I don't really want to go down that road.
