### ISSUE TITLE
feat - define image size of featured images in the infowindow

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/Google-Maps-Builder#80]
It looks like the "Large" image size (as defined in WP media settings) is currently being used as the image size loaded in the infowindow. The infowindow's display area is 335px, which means that "Large" images will often have an unnecessarily high resolution for this context. Performance could be optimized by allowing the user to define the image sized used. Mockup below:

![mb-featured-image-size-v01](https://cloud.githubusercontent.com/assets/1938671/9423953/9166a806-48a7-11e5-99df-a0d607a488f5.jpg)

**Comment by DevinWalker** [comment]
Yeah, definitely next release this would be a nice addition.

**Comment by mathetos** [comment]
At minimum we could create a filter to customize this.

**Comment by kevinwhoffman** [comment]
@mathetos I like that idea. Good quick fix in lieu of a UI addition.
