### ISSUE TITLE
No warning given when navigating away with unsaved changes

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/google-maps-builder#81]
Typical WordPress behavior is to warn you of unsaved changes if you attempt to navigate away from the post editor before saving/publishing/updating the post. It seems that none of the changes to the map trigger this warning, which means I can do anything in the map builder and navigate away without warning, thus losing any work done.

The one instance where this warning is triggered is when the map title is changed. Here's the warning I'm referencing:

![image](https://cloud.githubusercontent.com/assets/1938671/9424443/df35f344-48ba-11e5-91f5-2eae776c1502.png)

I'm recommending this warning show when any unsaved changes are present in the map builder.

**Comment by mathetos** [comment]
Good point.

**Comment by DevinWalker** [comment]
I'm not sure why WordPress (or CMB2) isn't handling this natively. I found: https://github.com/codedance/jquery.AreYouSure but I don't really want to go down this road if it's unnecessary. There's not a whole lot of documentation on this online after doing some research.

I don't think this is critical to hold up 2.0 milestone so I'm bumping that off this issue.

**Comment by DevinWalker** [comment]
I've done some more research on this and it appears it's working properly in most cases. Closing until I see more reports of this issue.
