### ISSUE TITLE
Redundant "Layers" language

### ISSUE THREAD

**Issue by mathetos** [WordImpress/google-maps-builder#83]
The "Map Layers" section is descriptive enough. No need to say "Bicycle LAYER". Let's shorten to 

### Map Layers ###
* Bicycle
* Traffic
* Transit

per https://github.com/WordImpress/google-maps-builder/issues/75

**Comment by DevinWalker** [comment]
Oh you fancy

**Comment by DevinWalker** [comment]
This is fixed
