### ISSUE TITLE
Maps Builder Pro - Display Options - Map Theme

### ISSUE THREAD

**Issue by paaljoachim** [WordImpress/Google-Maps-Builder#86]
Taking a closer look at Snazzy Map
![screen shot 2015-08-22 at 11 10 47 pm](https://cloud.githubusercontent.com/assets/5323259/9425887/1d240048-4923-11e5-9e56-2f8f1ddcec51.png)

Rewording and rethinking snazzy maps section.

Map Theme
(Text above the drop down) Select an optional preconfigured Snazzy Maps style.
Dropdown: - Custom -

Go to Snazzy Maps (link) to find additional custom map code. 
Toggle the following button: Insert Snazzy Map code
Inside the code text box: Paste the custom theme Json/JS code here.

**Comment by DevinWalker** [comment]
I agree we can fix this section up a bit to make it more clear. I don't think it's critical for 2.0 milestone though.
