### ISSUE TITLE
Upgrade: SCSS

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/google-maps-builder#9]
I'm addicted to the convenience of Scss - let's modernize the plugin to use it and compile using Gulp.

**Comment by DevinWalker** [comment]
Not a really high priority right now as we're not too CSS heavy yet

**Comment by DevinWalker** [comment]
OK OK... it is a priority now that we're getting into some heavier styling.

**Comment by mathetos** [comment]
Way to talk yourself into it.
