### ISSUE TITLE
Edit Map: Preview Changes -bug?-

### ISSUE THREAD

**Issue by paaljoachim** [WordImpress/google-maps-builder#90]
Hey

I have created two maps. In the Edit Map screen I press the Preview Changes OR View Map and get a 404 not found error on both. Map 1 opens a page with the following link: google-maps/test/ 

Map 2. Clicking preview first time I get this link: 
http://localhost:8888/Genesis-Sample/google-maps/gullerasen/?preview_id=56&preview_nonce=a0a8f4402d

Going back to edit map and clicking preview again I get this link
http://localhost:8888/Genesis-Sample/google-maps/gullerasen/

Interesting. 
The next time I click preview in the edit screen I get the longer link. 
The next time I click preview in the edit screen I get the shorter link.

Goes forth and back from long to short link to the 404 page.

**Comment by mathetos** [comment]
I have a feeling this is related to a common WordPress problem. After installing the plugin you should go to "Settings > Permalinks" and just re-save them. Then all should be fine.

This is something that really is problematic with CPT's and permalinks in WordPress generally and not specific to our plugin.

**Comment by paaljoachim** [comment]
ok
