### ISSUE TITLE
Deleting a marker creates a empty marker in the list

### ISSUE THREAD

**Issue by mathetos** [WordImpress/google-maps-builder#93]
ENVIRONMENT:
WP version: 4.2 and 4.3

Plugin:
Contact Form to Email Versione 1.1.6 
Google Analytics by Yoast Versione 5.4.5 
Shortcodes Ultimate Versione 4.9.8

Browser Chrome 44.0
___________________________________________

BUGS:
Bug (lite):
I have 10 markers listed; if I delete the marker n, I'll find a emptyv marker at n+1 position.
Example: I delete the marker 6, and I'll find a empty marker listed as marker number 6 (the old marker 6 will be the marker number 5...)

URL http://www.match2grow.it/chi-siamo/dove-siamo/

To reproduce it, simply I create a new map and put more then 4 marker in it and USING REMOVE MARKER delete one of the, not the last one. Save, and you will find the same number of marker, one of the, is empty.
___________________________________________

SCREENSHOTS:

___________________________________________

GENERAL FEEDBACK:
Very good plugin. Exactly what I was looking for, I tried the previous version was buggy...
Anyway the preview sometime put me in 404 page. Not important.
___________________________________________
REF: 789givePietro!ghs15z

**Comment by DevinWalker** [comment]
I believe I fixed this with https://github.com/WordImpress/google-maps-builder/issues/87

We need to check to see if the person who reported this bug used a version prior to that fix (it was over the weekend).

**Comment by DevinWalker** [comment]
Should be fixed now from #87
