### ISSUE TITLE
Option to have mousewheel zoom disabled by default

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Google-Maps-Builder#97]
People often feel annoyed when scrolling with their mouse wheels and Google Maps zoom in disrupting their way down the page. I propose we add an option to disable this option globally when creating new maps as this option is enabled by default now. I just got done creating a bunch of maps and realized I wanted this off from the beginning.

**Comment by DevinWalker** [comment]
... Or should it simply be disabled by default? @mathetos thoughts?

**Comment by mathetos** [comment]
Agree to global default and that that option would be OFF by default. If they REALLY want that option they'll have to override the default on the single map or the global.

**Comment by DevinWalker** [comment]
This is done
