### ISSUE TITLE
Invalid foreach on add new screen

### ISSUE THREAD

**Issue by pippinsplugins** [WordImpress/google-maps-builder#98]
I'm seeing this notice when adding a new map (before anything is saved):

( ! ) Warning: Invalid argument supplied for foreach() in /Users/pippin/Sites/edd/wp-content/plugins/google-maps-builder/includes/libraries/metabox/includes/CMB2_hookup.php on line 186

**Comment by pippinsplugins** [comment]
Note: this is happening in the Pro version. I don't know if it happens in the free one too.

**Comment by DevinWalker** [comment]
Yup, just fixed.

**Comment by DevinWalker** [comment]
Fixed as of 2f49805d17387d6159e98abb9d2780d9c0c832d5
