### ISSUE TITLE
404 when viewing a map

### ISSUE THREAD

**Issue by pippinsplugins** [WordImpress/google-maps-builder#99]
I'm not able to view a map's single post page: https://cloudup.com/cDh_FrVAZo5

Is this supposed to be viewable?

**Comment by pippinsplugins** [comment]
Scratch this, works now with latest.

Might want to double check: I think it only works once settings AND permalinks are saved.

**Comment by DevinWalker** [comment]
Seems like there's a permalink refresh missing somewhere... I'm going to test this again too.
